### ISSUE TITLE
Upgrade Website Manager to Technical Manager

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/.maintainers#19]
@oleksis - Would you be okay with upgrading your role to Technical Manager to encompass your contributions with social media and the discord?

You'd need to update your page.

**Comment by oleksis** [comment]
Sure I will the update the Role

**Comment by oleksis** [comment]
Think we can close this issue.

**Comment by kjaymiller** [comment]
You didn't update the title in `.maintainers`? - https://github.com/BlackPythonDevs/.maintainers/blob/main/roles/website-manager.md
