### ISSUE TITLE
Create Djangonauts Space Program

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/.maintainers#5]
- [X] Create Djangonaut Space Discord Channel
- [X] Create Djangonaut space Discord Role
- [X] Assign Leaders and Candidates role
- [X] Invite role to channel
- [X] Create Discussion Post

**Comment by VeldaKiara** [comment]
Could you add more information on this?

**Comment by kjaymiller** [comment]
right now there isn't much to update on. I could get Dawn Wages (who is one of the runners) added as a maintainer, but last I heard, she and Tim (Cummings) were discussing the best way to approach.

**Comment by kjaymiller** [comment]
### [Update]
I had a conversation with Tim Schilling on this.

There isn't much but one of the things that they would like to do is create some "Recommended candidates" That would allow us to nominate someone to join the next cohort. This would require some participation on our end as we'd need to do things like 

- small single-day workshops to get people up to speed
- host events with Djangonaut.space participants and leadership
