### ISSUE TITLE
BPD Leadership Summit 

### ISSUE THREAD

**Issue by VeldaKiara** [BlackPythonDevs/.maintainers#80]
# BPD Leadership Summit 

Due Date:  10th August

Organising the first, V1 leadership summit
More details can be found [here](https://docs.google.com/document/d/1zeN8MJT-_HP_1WvDTYzvDHgvtOLfLNIU9Oq5wlrq7pU/edit?usp=sharing)

@kjaymiller

**Comment by mihrab34** [comment]
@kjaymiller @activus-d  will this be documented under programs?

**Comment by activus-d** [comment]
@mihrab34 If it's decided that this will be a regular program and not a one-time event, then yes, we should document this under programs.

**Comment by VeldaKiara** [comment]
Its going to be a yearly event.

**Comment by kjaymiller** [comment]
> Reference in

@activus-d - Yes the intent is this will be held 1-2 times a year.
